[pytest]
addopts =
    -v
    -s
    --tracing=retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Critical tests
    regression: Full regression suite
    ui: Strictly UI
    api: Strictly API tests
    slow: Tests that take a long time to run
